In [ ]:
# needed imports
import pandas as pd

# load the data and make sure it loaded correctly
df = pd.read_csv("../data/student_performance_dataset.csv")
print("Dataset shape: ", df.shape)
display(df.head())
df.info()
display(df.describe())

# check for invalid data
print("Missing values:")
print(df.isnull().sum())
df["parental_education"] = df["parental_education"].fillna("MissingInfo")
print(df.isnull().sum())
print("Duplicate rows: ", df.duplicated().sum())
print("Duplicate student IDs: ", df["student_id"].duplicated().sum())
print("Negative study hours: ", (df["study_time_hours"] < 0).sum())
print("Negative sleep hours: ", (df["sleep_hours"] < 0).sum())
print("Invalid attendance: ", ((df["attendance_percent"] < 0) | (df["attendance_percent"] > 100)).sum())
print("Invalid previous grade: ", ((df["previous_grade"] < 0) | (df["previous_grade"] > 100)).sum())
print("Invalid exam scores: ", ((df["final_exam_score"] < 0) | (df["final_exam_score"] > 100)).sum())

# display the categorical variables and how often each value appears
categorical_columns = [
    "gender",
    "parental_education",
    "internet_access",
    "extracurricular_activities",
    "part_time_job",
    "final_grade"
]
for column in categorical_columns:
    print(df[column].value_counts(dropna=False))
    print()

# display the numeric variables
numeric_columns = [
    "study_time_hours",
    "attendance_percent",
    "sleep_hours",
    "previous_grade",
    "final_exam_score"
]

# calculate the quantiles and find any outliers
for column in numeric_columns:
    q1 = df[column].quantile(0.25)
    q3 = df[column].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    outliers = df[(df[column] < lower) | (df[column] > upper)]
    print(column, "- outliers: ", len(outliers))
    print(outliers[column].values)

# record the cleaned up data to a new file
df.to_csv("../data/student_performance_dataset_cleaned.csv")

Dataset shape:  (1000, 12)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  1000 non-null   int64
 1   gender                      1000 non-null   str
 2   study_time_hours            1000 non-null   float64
 3   attendance_percent          1000 non-null   float64
 4   sleep_hours                 1000 non-null   float64
 5   parental_education          898 non-null    str
 6   internet_access             1000 non-null   str
 7   extracurricular_activities  1000 non-null   str
 8   part_time_job               1000 non-null   str
 9   previous_grade              1000 non-null   float64
 10  final_exam_score            1000 non-null   float64
 11  final_grade                 1000 non-null   str
dtypes: float64(5), int64(1), str(6)
memory usage: 115.4 KB

,student_id,study_time_hours,attendance_percent,sleep_hours,previous_grade,final_exam_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,3.570700,85.092300,6.799500,69.740900,83.543500
std,288.819436,1.478559,9.270685,1.203527,12.613425,10.341333
min,1.000000,0.500000,54.800000,3.200000,31.300000,46.800000
25%,250.750000,2.600000,78.800000,5.900000,61.000000,76.075000
50%,500.500000,3.600000,85.200000,6.800000,69.600000,83.800000
75%,750.250000,4.500000,91.900000,7.600000,78.400000,91.525000
max,1000.000000,8.100000,100.000000,10.000000,100.000000,100.000000

Missing values:
student_id                      0
gender                          0
study_time_hours                0
attendance_percent              0
sleep_hours                     0
parental_education            102
internet_access                 0
extracurricular_activities      0
part_time_job                   0
previous_grade                  0
final_exam_score                0
final_grade                     0
dtype: int64
student_id                    0
gender                        0
study_time_hours              0
attendance_percent            0
sleep_hours                   0
parental_education            0
internet_access               0
extracurricular_activities    0
part_time_job                 0
previous_grade                0
final_exam_score              0
final_grade                   0
dtype: int64
Duplicate rows:  0
Duplicate student IDs:  0
Negative study hours:  0
Negative sleep hours:  0
Invalid attendance:  0
Invalid previous grade:  0
Invalid exam scores:  0
gender
Female    510
Male      490
Name: count, dtype: int64

parental_education
High School    356
Bachelors      308
Masters        184
MissingInfo    102
PhD             50
Name: count, dtype: int64

internet_access
Yes    854
No     146
Name: count, dtype: int64

extracurricular_activities
Yes    572
No     428
Name: count, dtype: int64

part_time_job
No     684
Yes    316
Name: count, dtype: int64

final_grade
B    354
A    284
C    261
D     89
F     12
Name: count, dtype: int64

study_time_hours - outliers:  4
[8.1 7.4 7.4 7.4]
attendance_percent - outliers:  6
[56.3 55.8 58.  55.6 54.8 59. ]
sleep_hours - outliers:  2
[3.2 3.3]
previous_grade - outliers:  3
[31.3 34.5 33.5]
final_exam_score - outliers:  1
[46.8]

OSError: Cannot save file into a non-existent directory: 'data'